#!/usr/bin/env bash

# Exit on error, unset variables and pipeline errors
set -euo pipefail

# This is just an example.
# Only run some fast checks, the rest is done on CI
# because it would be too annoing to run on every commit.
# Feel free to ignore any of these with --no-verify when not pushing to master.

# See .github/workflows/* for explanations.

cargo fmt -- --check

! ( grep --recursive --color=auto --exclude-dir=.git --exclude-dir=target --exclude-dir=screenshots [F]IXME . && echo "The lines above this message must be fixed (or marked as todo/later in uppercase, not fixme)" )

! ( grep --recursive --color=auto --exclude-dir=.git --exclude-dir=target --exclude-dir=screenshots --exclude=debug.rs cvars\.d_dbg . && echo "The d_dbg* cvars should not be used in committed code. Maybe you forgot to remove debug code?" )

! ( grep --extended-regexp --no-filename --only-matching "pub fn +[a-z_]+" $(grep --recursive --files-with-matches "impl [A-Za-z]*FrameCtx" src) | grep --extended-regexp --invert-match "pub fn (new|ctx|update)$" | sort | uniq --count | grep --invert-match " *1 " && echo "Frame context methods present on multiple contexts should have different names to prevent confusion between client/server/common." )

! ( find data | grep [A-Z] && echo "Asset names/paths must be all lowercase" )
